---
- name: Install Apache and Deploy App
  hosts: webservers
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Ensure Apache2 is running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Install git (needed to clone repo)
      apt:
        name: git
        state: present

    - name: Clone app repo to /var/www/html
      git:
        repo: 'https://github.com/Jeevan-priyanka-Satyavolu/myapp-ansible.git'
        dest: /var/www/html
        force: yes

    - name: Set proper permissions on /var/www/html
      file:
        path: /var/www/html
        owner: www-data
        group: www-data
        recurse: yes

    - name: Restart Apache to apply changes
      service:
        name: apache2
        state: restarted
